#############################
### ANIMATIONS ###
#############################

animations {
    enabled = true

    # Custom easing curve
    bezier = easeOut, 0.25, 1, 0.5, 1

    # Windows
    animation = windows, 1, 5, easeOut, slide
    animation = windowsIn, 1, 5, easeOut, slide
    animation = windowsOut, 1, 5, easeOut, slide

    # Fade
    animation = fade, 1, 4, easeOut

    # Border
    animation = border, 1, 5, easeOut

    # Border angle
    animation = borderangle, 1, 8, easeOut

    # Workspace switching
    animation = workspaces, 1, 5, easeOut

    # Workspace fade
    animation = specialWorkspace, 1, 5, easeOut
}