#############################
### AUTOSTART ###############
#############################

exec-once = clipse -listen
exec-once = mako --config ~/.config/mako/config
exec-once = wl-gammarelay-rs
exec-once = hypridle
exec-once = flameshot
exec-once = kdeconnectd
exec-once = kdeconnect-indicator
exec-once = $scripts/set-wallpaper.sh
exec-once = $scripts/night-light.sh
exec-once = silent sleep 4; brave
exec-once = [workspace 3 silent] sleep 4; spotify
exec-once = sleep 5; wezterm start --class scratchpad
