#############################
### AUTOSTART ###############
#############################

exec-once = wl-clipboard
exec-once = clipse -listen
exec-once = waybar
exec-once = mako --config ~/.config/mako/config
exec-once = wl-gammarelay-rs
exec-once = hypridle
exec-once = flameshot
exec-once = kdeconnectd
exec-once = kdeconnect-indicator
exec-once = $scripts/set-wallpaper.sh
exec-once = $scripts/night-light.sh
exec-once = sleep 2; /home/tig/tig-dotfiles/scripts/night-light.sh
exec-once = silent sleep 4; brave
exec-once = [workspace 3 silent] sleep 4; spotify
exec-once = sleep 5; wezterm start --class scratchpad
exec-once = /etc/profiles/per-user/tig/bin/kdeconnectd
exec-once = kdeconnect-indicator
exec-once = python3 /home/tig/tig-dotfiles/scripts/infinite_desktop_core.py 1.6 > /tmp/infinite-desktop.log 2>&1
#exec-once = /home/tig/tig-dotfiles/scripts/set-wallpaper.sh
