input {
    kb_layout = us,ara
    kb_options = caps:escape_shifted_capslock,grp:alt_shift_toggle
    numlock_by_default = true
    sensitivity = -0.3  # -1.0 to 1.0, 0 means no modification
    accel_profile = flat  # or "adaptive"
}