misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    focus_on_activate = true
    allow_session_lock_restore = true
}
group {
  group_on_movetoworkspace = true
  groupbar {
    enabled = false
  }
}
xwayland {
  force_zero_scaling = true
}
