windowrule = match:class .*, group set
windowrule = match:class ^(float)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(qt5ct)$, float on
windowrule = match:class ^(qt6ct)$, float on
windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, center 1
windowrule = match:class ^(blueman-manager)$, center 1
windowrule = match:class ^(nm-connection-editor)$, center 1
windowrule = match:class ^(qt5ct)$, center 1
windowrule = match:class ^(qt6ct)$, center 1
windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:class ^(flameshot)$, float on
windowrule = match:class ^(flameshot)$, center 1
windowrule = match:class ^(brave-nngceckbapebfimnlniiiahkandclblb-Default)$, float on
windowrule = match:class ^(scratchpad)$, float on
windowrule = match:class ^(scratchpad)$, size 90% 90%
windowrule = match:class ^(scratchpad)$, center 1
windowrule = match:class ^(scratchpad)$, workspace special:scratchpad
windowrule = match:title ^(.*)(is sharing your screen.)$, workspace 10 silenta