$mainMod = SUPER
$terminal = wezterm
$browser = brave
$fileManager = nautilus
$launcher = rofi -show drun
$scripts = $DOTFILES_DIR/scripts
$lock = hyprlock
$screenshot = flameshot gui
$clipboard = wezterm start --class float clipse
$bluetooth = wezterm start --class float bluetuith
$colorpicker = hyprpicker -a
