$mainMod = SUPER
$terminal = wezterm
$browser = brave
$fileManager = nautilus
$launcher = rofi -show drun
$scripts = /home/tig/tig-dotfiles/scripts
$screenshot = flameshot gui
$lock = hyprlock
$screenshot = flameshot gui
$clipboard = wezterm start --class float clipse
$bluetooth = wezterm start --class float bluetuith
$colorpicker = hyprpicker -a