source = ~/.config/hypr/configs/variables.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/general.conf
source = ~/.config/hypr/configs/decoration.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/misc.conf
source = ~/.config/hypr/configs/workspaces.conf
source = ~/.config/hypr/configs/binds.conf
source = ~/.config/hypr/configs/mouse.conf
source = ~/.config/hypr/configs/rules.conf
source = ~/.config/hypr/configs/autostart.conf